/*
	FRMFootballManagementServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface FRMFootballManagementServiceExample : NSObject {
}
-(void)run;
@end
		