/*
	FMRMatch.h
	The implementation of properties and methods for the FMRMatch object.
	Generated by SudzC.com
*/
#import "FMRMatch.h"

#import "FMRArrayOfCard.h"
#import "FMRArrayOfGoal.h"
#import "FMRArrayOfPlayer.h"
#import "FMRArrayOfReferee.h"
#import "FMRTeam.h"
#import "FMRTeam.h"
#import "FMRTournament.h"
@implementation FMRMatch
	@synthesize Cards = _Cards;
	@synthesize Goals = _Goals;
	@synthesize Id = _Id;
	@synthesize MatchDate = _MatchDate;
	@synthesize Players = _Players;
	@synthesize Referees = _Referees;
	@synthesize Team = _Team;
	@synthesize Team1 = _Team1;
	@synthesize Tournament = _Tournament;

	- (id) init
	{
		if(self = [super init])
		{
			self.Cards = [[NSMutableArray alloc] init];
			self.Goals = [[NSMutableArray alloc] init];
			self.MatchDate = nil;
			self.Players = [[NSMutableArray alloc] init];
			self.Referees = [[NSMutableArray alloc] init];
			self.Team = nil; // [[FMRTeam alloc] init];
			self.Team1 = nil; // [[FMRTeam alloc] init];
			self.Tournament = nil; // [[FMRTournament alloc] init];

		}
		return self;
	}

	+ (FMRMatch*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Cards = [[FMRArrayOfCard createWithNode: [Soap getNode: node withName: @"a:Cards"]] object];
			self.Goals = [[FMRArrayOfGoal createWithNode: [Soap getNode: node withName: @"a:Goals"]] object];
			self.Id = [[Soap getNodeValue: node withName: @"a:Id"] intValue];
			self.MatchDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"a:MatchDate"]];
			self.Players = [[FMRArrayOfPlayer createWithNode: [Soap getNode: node withName: @"a:Players"]] object];
			self.Referees = [[FMRArrayOfReferee createWithNode: [Soap getNode: node withName: @"a:Referees"]] object];
			self.Team = [[FMRTeam createWithNode: [Soap getNode: node withName: @"a:Team"]] object];
			self.Team1 = [[FMRTeam createWithNode: [Soap getNode: node withName: @"a:Team1"]] object];
			self.Tournament = [[FMRTournament createWithNode: [Soap getNode: node withName: @"a:Tournament"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Match"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Cards != nil && self.Cards.count > 0) {
			[s appendFormat: @"<a:Cards>%@</a:Cards>", [FMRArrayOfCard serialize: self.Cards]];
		} else {
			[s appendString: @"<a:Cards xsi:nil=\"true\"/>"];
		}
		if (self.Goals != nil && self.Goals.count > 0) {
			[s appendFormat: @"<a:Goals>%@</a:Goals>", [FMRArrayOfGoal serialize: self.Goals]];
		} else {
			[s appendString: @"<a:Goals xsi:nil=\"true\"/>"];
		}
		[s appendFormat: @"<a:Id>%@</a:Id>", [NSString stringWithFormat: @"%i", self.Id]];
		if (self.MatchDate != nil) {
            [s appendFormat: @"<a:MatchDate>%@</a:MatchDate>", [Soap getDateString: self.MatchDate]];
        } else {
            [s appendString: @"<a:MatchDate xsi:nil=\"true\"/>"];
        }
		if (self.Players != nil && self.Players.count > 0) {
			[s appendFormat: @"<a:Players>%@</Players>", [FMRArrayOfPlayer serialize: self.Players]];
		} else {
			[s appendString: @"<a:Players xsi:nil=\"true\"/>"];
		}
		if (self.Referees != nil && self.Referees.count > 0) {
			[s appendFormat: @"<a:Referees>%@</Referees>", [FMRArrayOfReferee serialize: self.Referees]];
		} else {
			[s appendString: @"<a:Referees xsi:nil=\"true\"/>"];
		}
		if (self.Team != nil) {
            [s appendString: [self.Team serialize: @"a:Team"]];
        } else {
            [s appendString: @"<a:Team xsi:nil=\"true\"/>"];
        }
		if (self.Team1 != nil) {
            [s appendString: [self.Team1 serialize: @"a:Team1"]];
        } else {
            [s appendString: @"<a:Team1 xsi:nil=\"true\"/>"];
        }
		if (self.Tournament != nil) {
            [s appendString: [self.Tournament serialize: @"a:Tournament"]];
        } else {
            [s appendString: @"<a:Tournament xsi:nil=\"true\"/>"];
        }
        
		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];
        [s appendString:@" xmlns:a=\"http://schemas.datacontract.org/2004/07/FootballManagement.Commons.Entities\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:z=\"http://schemas.microsoft.com/2003/10/Serialization/\""];
		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[FMRMatch class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
